# Generated by Django 3.1.7 on 2021-03-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Myplaylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('writer', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('body', models.TextField()),
                ('list_type', models.CharField(max_length=50)),
                ('list_genre', models.CharField(max_length=50)),
                ('list_play', models.CharField(max_length=50)),
                ('list_image', models.ImageField(upload_to='playlist/')),
            ],
        ),
    ]
