# Generated by Django 3.1.7 on 2021-03-16 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Myplaylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('writer', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('body', models.TextField()),
                ('list_type', models.CharField(max_length=50)),
                ('list_genre', models.CharField(max_length=50)),
                ('list_play', models.CharField(blank=True, max_length=50, null=True)),
                ('list_image', models.ImageField(upload_to='playlist/')),
                ('like', models.IntegerField(blank=True, null=True)),
                ('like_users', models.ManyToManyField(related_name='like_playlist', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
